### ISSUE TITLE
How to deal with ShippingMethodType?

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/marello#43]
Hello,

when I create an order with REST, shippingMethodType is NULL and posibility to pass parameter with REST is not given. I set this field in a quick and dirty solution during workflow transition like this

```
                  - @call_method:
                        object: $order
                        method: setShippingMethodType
                        method_parameters:
                            - primary
```

Exists a common way to create order from Rest?
What means "primary" and which other values do exist either?

Thanks
